### ISSUE TITLE
Crash when trying to access Fluid Traders

### ISSUE THREAD

**Issue by Jorgee9001** [Lightman314/LCTech#1]
Game crashes when trying to access a fluid trader.

Minecraft 1.16.5
Forge: 36.2.22
Mod Version: 1.16.4-0.0.0.5

Crashlog:

[crash-2021-12-19_16.26.14-client.txt](https://github.com/Lightman314/LCTech/files/7741628/crash-2021-12-19_16.26.14-client.txt)

**Comment by Lightman314** [comment]
My apologies for this issue, I need to update the fluid traders to be compatible with the latest lightmans currency changes. Sadly this may take a few weeks as my computer is currently in the shop so I can't work on my mods at the moment.

**Comment by Jorgee9001** [comment]
That's fine! So as a temporary fix, should I downgrade the base currency mod?

**Comment by Lightman314** [comment]
That should work as a temp fix it until I've updated it, yeah. I believe it should still be compatible with any Lightman's Currency version at or below v1.0.1.1, as it's only the latest version (v1.0.1.2) that changed how the free status of a trades price is handled (which is what the crash report is complaining about, cause I removed the isFree/setFree functions from the trade data when I move it's functionality to the price data).

In hindsight, I probably should have left the old functions in the trade data to keep backwards compatibility, so I might also patch those back in as deprecated functions in a future update to prevent future issues such as these.

**Comment by Lightman314** [comment]
I've posted a fix to curseforge (v1.16.4-0.0.0.6) that updates the fluid traders with the new free-state handling, and it should be available for download in a few minutes. Keep in mind that it does require the latest version (v1.0.1.2) of Lightman's Currency, so you'll likely need to update both.
