### ISSUE TITLE
Energy trader doesn't stop exporting energy

### ISSUE THREAD

**Issue by Nemirel345** [Lightman314/LCTech#10]
Setting up the energy trader to purchase energy from batteries and always exporting it, the trader doesn't stop exporting when its internal battery empties and continues draining, making the internal energy storage go negative.
![2023-01-29_06 02 29](https://user-images.githubusercontent.com/16631095/215322006-1747baf2-5b85-4eeb-82c6-00dbefb1f6de.png)
![2023-01-29_06 03 03](https://user-images.githubusercontent.com/16631095/215322007-d7a2a2a8-c291-46d3-bcf3-ffe12c868570.png)

**Comment by Lightman314** [comment]
Fixed in v0.1.0.4. Thank you for reporting.

**Comment by Nemirel345** [comment]
Awesome, could you update the 1.19.2 file with this fix, please?

**Comment by Lightman314** [comment]
And done.

**Comment by Nemirel345** [comment]
Thank you so much!
