### ISSUE TITLE
[Forge 1.18.2] Buying fluids using Fluid Tap causes server crash.

### ISSUE THREAD

**Issue by wiloxe** [Lightman314/LCTech#12]
When buying fluids from a fluid tap it completes the transaction and crashes the server, after restart you will have 1 bucket of the fluid bought and coins used.

Crash report: https://pastebin.com/PFV7nJHc

Forge: 40.2.1
Lightman's Currency: 1.18.2-2.1.1.0b
LC Tech: 1.18.2-0.1.1.0

**Comment by Lightman314** [comment]
It would appear I missed something when trying to make sure the 2.1.1.0 update didn't break compatibility with LC Tech.
I needed to update LC Tech anyways, so I should be able to get this fixed real quick.

**Comment by Lightman314** [comment]
Should be fixed in LC Tech v0.1.1.1, although LC will need to be updated to v2.1.1.0c as well, as there was an unintended typo that made it impossible to properly update LC Tech to the new systems added in v2.1.1.0.
