### ISSUE TITLE
[1.20.1] LC Tech not loading on multiplayer server with latest Lightman's Currency

### ISSUE THREAD

**Issue by HockeyZman2000** [Lightman314/LCTech#13]
[latest.log](https://github.com/Lightman314/LCTech/files/12861183/latest.log)

Upon inspecting the log, the discord integration might also have something to do with it.

Lightman's Currency 2.1.2.4
LC Tech 0.2.0.1
(just in case) Lightman's Discord Integration 0.2.0.3
Forge 47.1.47

**Comment by Lightman314** [comment]
Yeah, I need to update LC Tech to make it compatible with the changes made in LC 2.1.2.4. I'll try to have a build out either tonight or tomorrow.

**Comment by Lightman314** [comment]
Should be fixed in LC Tech v0.2.0.2
