### ISSUE TITLE
[1.20.1] Upgrades cannot be crafted

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LCTech#14]
Apparently the recipe is wrong according to my dedicated server.

> [main/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe lctech:upgrades/energy_capacity_upgrade_2: com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'minecraft:smithing'

LcTech: 1.20.1-0.2.1.3b

**Comment by Lightman314** [comment]
Fixed in v0.2.1.3c
