### ISSUE TITLE
[1.20.1] No bank account spam

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LCTech#16]
I have a **fluid trader interface terminal** and an **energy trader interface terminal**, every time I restart the dedicated server for some reason it desynchronizes from my bank account and in the console of my dedicated server it spams "No bank account for player with id..." every second, until I break it and put it back or transfer the owner to myself.

forge: 1.20.1 - 47.2.0
lightmanscurrency-1.20.1-2.2.2.1a
lctech-1.20.1-0.2.1.5

**Comment by Lightman314** [comment]
Please attach a copy of the latest.log file so that I can see the exact log message you're having issues with.

**Comment by DankestO** [comment]
[latest.log](https://github.com/user-attachments/files/16149929/latest.log)

**Comment by DankestO** [comment]
It seems that the previous Lightman's Currency update solved the problem for me, at least I haven't seen that spam again, thank you!
