### ISSUE TITLE
[1.20.1] Dedicated server crashes when placing a netherite fluid tank

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LCTech#17]
I was testing the new netherite liquid tanks, it seems that they lose their texture if you place a block on top of them, and when I wanted to place a supplementaries faucet on top of them to fill the tank with honey, the whole server crashed.

[crash-2024-07-08_18.41.09-server.txt](https://github.com/user-attachments/files/16132169/crash-2024-07-08_18.41.09-server.txt)

forge: 1.20.1 - 47.2.0
lightmanscurrency-1.20.1-2.2.2.3
lctech-1.20.1-0.2.1.6

**Comment by Lightman314** [comment]
Should be fixed in LC Tech v0.2.1.7
