### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LCTech#5]
would it be possible to make a remote stockpile for servers like the buyer can sell items/fluid or energy from is server stockpile to a server or buy to his stockpile.
and could you make the ernergy amounts and or fluid amounts configurable? battery only 100k while the trader can hold 5M is kinda pain to fill up because the server doesnt have input or output sides

**Comment by ZEROX7** [comment]
or just make the battery upgradable to hold more?

**Comment by Lightman314** [comment]
I do eventually plan on adding config values for nearly every energy/fluid object (from tanks, to trader defaults, to capacity upgrade amounts, fluid/energy trade quantity limits, etc.).

**Comment by Lightman314** [comment]
Done!
