### ISSUE TITLE
LC Tech has failed to load correctly 1.19

### ISSUE THREAD

**Issue by Chromeyay** [Lightman314/LCTech#7]
Not sure if its something I'm doing wrong but the mod entirely doesn't work at the moment
[latest.log](https://github.com/Lightman314/LCTech/files/9154578/latest.log)
[crash-2022-07-20_17.18.09-fml.txt](https://github.com/Lightman314/LCTech/files/9154593/crash-2022-07-20_17.18.09-fml.txt)

**Comment by Lightman314** [comment]
Ya know, I fixed this exact thing in LC, but it completely slipped my minds that I'd need to fix it for LC Tech too...

TLDR: Forge has been making a lot of internal changes (renaming classes to match vanilla naming, reworking how certain client data is registered, etc.) especially in 41.0.64 & 41.0.94, so I need to update my mods code to match those newly changed classes/functions/registration, etc.

**Comment by Lightman314** [comment]
Should be fixed in v0.0.5.9b
